export const APPWRITE_CONFIG = {
  CLIENT: {
    ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!,
    PROJECT_ID: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!,
    DATABASE_ID: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!,
    API_KEY: process.env.NEXT_PUBLIC_APPWRITE_API_KEY!,
    COLLECTIONS: {
      COMPANIES: process.env.NEXT_PUBLIC_APPWRITE_COMPANIES_COLLECTION_ID!,
      ADDRESSES: process.env.NEXT_PUBLIC_APPWRITE_ADDRESS_COLLECTION_ID!,
      INVITATIONS: process.env.NEXT_PUBLIC_APPWRITE_INVITES_COLLECTION_ID!,
      USERS: process.env.NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID!,
      PRODUCTS: process.env.NEXT_PUBLIC_APPWRITE_PRODUCTS_COLLECTION_ID!,
      PRICES: process.env.NEXT_PUBLIC_APPWRITE_PRICES_COLLECTION_ID!,
      PLANS: process.env.NEXT_PUBLIC_APPWRITE_PLANS_COLLECTION_ID!,
    },
    BUCKET: {
      GIROFLEX: process.env.NEXT_PUBLIC_APPWRITE_GIROFLEX_BUCKET_ID!
    },
    TEAMS: {
      SAAS_TEAM_ID: process.env.NEXT_PUBLIC_APPWRITE_SAAS_TEAM_ID!,
    }
  },
  SERVER: {
    ENDPOINT: process.env.APPWRITE_ENDPOINT!,
    PROJECT_ID: process.env.APPWRITE_PROJECT_ID!,
    DATABASE_ID: process.env.APPWRITE_DATABASE_ID!,
    API_KEY: process.env.APPWRITE_API_KEY!,
    COLLECTIONS: {
      COMPANIES: process.env.APPWRITE_COMPANIES_COLLECTION_ID!,
      ADDRESSES: process.env.APPWRITE_ADDRESS_COLLECTION_ID!,
      INVITATIONS: process.env.APPWRITE_INVITES_COLLECTION_ID!,
      USERS: process.env.APPWRITE_USERS_COLLECTION_ID!,
      PRODUCTS: process.env.APPWRITE_PRODUCTS_COLLECTION_ID!,
      PRICES: process.env.APPWRITE_PRICES_COLLECTION_ID!,
      PLANS: process.env.APPWRITE_PLANS_COLLECTION_ID!,
    },
    BUCKET: {
      GIROFLEX: process.env.APPWRITE_GIROFLEX_BUCKET_ID!
    },
    TEAMS: {
      SAAS_TEAM_ID: process.env.APPWRITE_SAAS_TEAM_ID!,
    }
  }
};

export const USER_LABELS = {
  SAAS_OWNER: 'saas_owner',
  SAAS_CLIENT: 'saas_client',
  COMPANY_OWNER: 'company_owner',
  COMPANY_EMPLOYEE: 'company_employee',
  COMPANY_CLIENT: 'company_client',
};